.TH BLIND-TRANSPOSE 1 blind
.SH NAME
blind-transpose - Transpose a video
.SH SYNOPSIS
.B blind-transpose
.SH DESCRIPTION
.B blind-transpose
reads a video from stdin and prints it,
transposed, to stdout.
.P
To transpose a videos means to swap the
X and Y coordinates.
.SH AUTHORS
Mattias Andree
.RI < maandree@kth.se >
