.TH BLIND-ROTATE-270 1 blind
.SH NAME
blind-rotate-270 - Rotate a video 270 degrees clockwise
.SH SYNOPSIS
.B blind-rotate-270
.SH DESCRIPTION
.B blind-rotate-270
reads a video from stdin and prints it, rotated
270 degrees clockwise (90 degrees anti-clockwise),
to stdout.
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
